Products page - HeroSectionOfProducts
CAFECA-IO/iSunCoin-official pull request #45
Opened 2024-06-21 10:43 UTC by godmmt

unfinished

2024-06-25 11:15 UTC, Luphia requested changes

2024-06-25 11:15 UTC, Luphia commented on src/components/carousel/carousel_kv.tsx
- remove /* eslint-disable @typescript-eslint/no-unused-vars */
- use '@' for import path

2024-06-26 02:06 UTC, godmmt commented on src/components/carousel/carousel_kv.tsx
use '@' for import path

這部分請問是哪個部分要改？
目前專案內部文件的引入路徑已用 @ 引入

以下部分是從 node_modules 中引入的第三方依賴項，應該是無法用 @ 引入：
```
import Slider from 'react-slick';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
```

2024-06-26 02:52 UTC, Luphia commented on src/components/carousel/carousel_kv.tsx
誤判了，import 路徑沒有問題

2024-06-26 02:53 UTC, Luphia approved these changes
- no bug found

2024-06-26 09:56 UTC, merged