header & folder structures
CAFECA-IO/iSunCoin-official pull request #92
Opened 2024-08-08 06:16 UTC by godmmt

### DEVELOP

- [ ] archive v1 landing page codes and reorganize folder structure
- [ ] define the structures of use / develop / autonomy
- [ ] Header

### CHECK LIST

- [Naming convention](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/coding-convention/naming-convention.md) verification: checked
- Coding style verification: checked
- new recursive: 0
- high risk: 0
- new sql: 0
- new loop: 0
- new Library: 0
- new Class / Component: 0

2024-08-08 10:58 UTC, Luphia requested changes

2024-08-08 10:58 UTC, Luphia commented on src/components/common/Footer.tsx
> +import packageJson from '../../../package.json';
- use '@package'

2024-08-09 02:02 UTC, godmmt commented on src/components/common/Footer.tsx
> +import packageJson from '../../../package.json';
ok

2024-08-09 10:42 UTC, Luphia approved these changes
- no bug found

2024-08-09 10:42 UTC, merged